### ISSUE TITLE
tracsubtickets.api doesn't work after a 1.2.2 to 1.4.2 trac upgrade

### ISSUE THREAD

**Issue by guillaume1987** [trac-hacks/trac-subtickets-plugin#32]
After successfully upgrading Trac from 1.2.2 to 1.4.2, I faced some issues regarding a few plugins, particularly with tracsubtickets.api (tracsubtickets.web_ui works ok), raising the following error after a `trac-admin env/ upgrade `:
```
2021-01-07 14:36:35,069 Trac[env] ERROR: Component <Component tracsubtickets.api.SubTicketsSystem> failed with 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/trac/env.py", line 387, in component_guard
    yield
  File "/usr/local/lib/python2.7/dist-packages/trac/env.py", line 750, in needs_upgrade
    if participant.environment_needs_upgrade():
  File "build/bdist.linux-x86_64/egg/tracsubtickets/api.py", line 99, in environment_needs_upgrade
    """, (db_default.name,)):
  File "/usr/local/lib/python2.7/dist-packages/trac/db/util.py", line 129, in execute
    cursor.execute(query, params if params is not None else [])
  File "/usr/local/lib/python2.7/dist-packages/trac/db/util.py", line 73, in execute
    return self.cursor.execute(sql_escape_percent(sql), args)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/cursors.py", line 163, in execute
    result = self._query(query)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 724, in _read_query_result
    result.read()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
ProgrammingError: (1064, u"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'system WHERE name='subtickets'' at line 1")
```

I tried upgrading the plugin from version 0.5.3 (which worked correctly with Trac 1.2.2) to 0.5.5.dev0, but the problem remains. Any idea why?

My configuration: 

```
User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0
Trac 1.4.2 
Babel 2.6.0 
Docutils 0.16 
Genshi 0.7.3 (with speedups) 
GIT 2.25.1 
Jinja2 2.10.3 
mod_wsgi 4.6.8 (WSGIProcessGroup voxygen WSGIApplicationGroup %{GLOBAL})
MySQL server: "8.0.22-0ubuntu0.20.04.3", client: "0.10.1", thread-safe: True
Pygments 2.3.1 
pymysql 0.10.1 
Python 2.7.18 (default, Aug 4 2020, 11:16:42) [GCC 9.3.0] 
pytz 2019.3 
setuptools 44.1.1 
Subversion 1.13.0 (r1867053) 
jQuery 1.12.4 
jQuery UI 1.12.1 
jQuery Timepicker 1.6.3 
```

**Comment by rjollos** [comment]
`system` is a reserved word since [MySQL 8.0.3](https://dev.mysql.com/doc/refman/8.0/en/keywords.html).
